services:
  logistica-service:
    build: .
    container_name: logistica-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5008:5008"
    networks:
      - portal-b2b-network

  logistica-front:
    build: ./frontend
    container_name: logistica-front
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - logistica-service
    networks:
      - portal-b2b-network

networks:
  portal-b2b-network:
    external: true
