services:
  logistica-service:
    build: .
    container_name: logistica-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - "5008:5008"
    networks:
      - portal-b2b-network

  logistica-front:
    build: ./frontend
    container_name: logistica-front
    restart: unless-stopped
    ports:
      - "8088:80"
    depends_on:
      - logistica-service
    networks:
      - portal-b2b-network

networks:
  portal-b2b-network:
    external: true
